import Head from 'next/head';

export default function TermsAndConditions() {
  return (
    <>
      <Head>
        <title>Terms and Conditions - AskYourContract.ai</title>
        <meta name="robots" content="noindex" />
      </Head>
      <div className="min-h-screen px-6 py-12 bg-gradient-to-b from-slate-950 to-slate-900 text-white">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>

          <p className="mb-4">
            These Terms and Conditions ("Terms") govern your use of AskYourContract.ai (the “Service”), operated by AskYourContract.ai ("we", "our", "us").
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">1. Use of the Service</h2>
          <p className="mb-4">
            By accessing or using AskYourContract.ai, you agree to these Terms. You must be at least 18 years old or have legal guardian consent.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">2. Intellectual Property</h2>
          <p className="mb-4">
            All content, features, and functionality on AskYourContract.ai are owned by us and are protected by intellectual property laws.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">3. User Content</h2>
          <p className="mb-4">
            You retain ownership of the legal documents you upload. We process them solely to provide our AI-powered services.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">4. AI Limitations</h2>
          <p className="mb-4">
            The output generated by our AI is for informational purposes only and does not constitute legal advice.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">5. Payment & Subscription</h2>
          <p className="mb-4">
            Some features may require a paid subscription. By subscribing, you agree to our billing terms via Paddle.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">6. Termination</h2>
          <p className="mb-4">
            We may suspend or terminate access to the Service for violations of these Terms or for security reasons.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">7. Changes to Terms</h2>
          <p className="mb-4">
            We reserve the right to update these Terms. Continued use after changes constitutes acceptance.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-2">8. Contact</h2>
          <p className="mb-4">
            For any questions, contact us at: <a href="mailto:contact@askyourcontractai.com" className="underline text-blue-400">contact@askyourcontractai.com</a>
          </p>
        </div>
      </div>
    </>
  );
}